from enum import Enum


class AppointmentStatus(Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class AppointmentType(Enum):
    CONTROL = "CONTROL"
    FOLLOW_UP = "FOLLOW_UP"
    EMERGENCY = "EMERGENCY"
    SURGERY = "SURGERY"
    OTHER = "OTHER"


class Specialty(Enum):
    CARDIOLOGY = "CARDIOLOGY"
    DERMATOLOGY = "DERMATOLOGY"
    ENDOCRINOLOGY = "ENDOCRINOLOGY"
    GASTROENTEROLOGY = "GASTROENTEROLOGY"
    GYNECOLOGY = "GYNECOLOGY"
    HEMATOLOGY = "HEMATOLOGY"
    NEPHROLOGY = "NEPHROLOGY"
    NEUROLOGY = "NEUROLOGY"
    ONCOLOGY = "ONCOLOGY"
    OPHTHALMOLOGY = "OPHTHALMOLOGY"
    ORTHODONTICS = "ORTHODONTICS"
    OTORHINOLARYNGOLOGY = "OTORHINOLARYNGOLOGY"
    PEDIATRICS = "PEDIATRICS"
    PSYCHIATRY = "PSYCHIATRY"
    PULMONOLOGY = "PULMONOLOGY"
    RHEUMATOLOGY = "RHEUMATOLOGY"
    TRAUMATOLOGY = "TRAUMATOLOGY"
    UROLOGY = "UROLOGY"
    OTHER = "OTHER"


class Policlinic(Enum):
    HOSPITAL = "HOSPITAL"
    CLINIC = "CLINIC"
    OTHER = "OTHER"
    ODONTOLOGY = "ODONTOLOGY"


class FilterRuleType(Enum):
    NOT_VALID_SPECIALTY = "NotValidSpecialty"
    NOT_VALID_DOCTOR = "NotValidDoctor"
    NOT_VALID_DOCTOR_DNI = "NotValidDoctorDNI"
    VALID_APPOINTMENT_TYPE = "ValidAppointmentType"
    VALID_APPOINTMENT_TYPE_POLICLINIC = "ValidAppointmentTypePoliclinic"


class ContactRuleType(Enum):
    CONTACT_STATUS = "ContactStatus"
    CONTACT_DOCTOR = "ContactDoctor"
